### ISSUE TITLE
Modulus doesn't match word list length and generator is biased

### ISSUE THREAD

**Issue by atoponce** [mike-hearn/useapassphrase#4]
The word list length is 5,837 unique words, but the modulus is 5,852. I'm guessing this is an oversight that slipped in as part of testing, but wasn't fixed before pushing to production.

https://github.com/mike-hearn/useapassphrase/blob/79c2066ed9978e90a262bf454826f80ca30dc6b7/js/script.js#L14-L18

Also, the generator is biased. You are generating 4 32 bit numbers, but using them with a modulus that does not divide 2^32 evenly. With modulus 5837,  the first 3,467 words in the word list will be more likely to be chosen than the rest.

https://github.com/mike-hearn/useapassphrase/blob/79c2066ed9978e90a262bf454826f80ca30dc6b7/js/script.js#L4-L8

Instead, you need a uniform generator that discards numbers outside of a range that is a multiple of 5837. Something like this:

    // Cryptographically and uniformly generated random numbers 
    numberOfWords = parseInt(numberOfWords);
    var min = 3467; // force the range of [`min', 2**32] to be a multiple of 5837
    var array = new Uint32Array(numberOfWords);
    const my_crypto = window.crypto || window.msCrypto;
    do {
        my_crypto.getRandomValues(array);
        var too_small = array.some(function(e) { return e<min; });
    } while (too_small);

Now you will get each element modulo 5837 uniformly:

    var generatedPasswordArray = [];
    for (var i = 0; i < array.length; i++) {
        var index = (array[i] % 5837);
        generatedPasswordArray.push(wordlist[index]);
    }

**Comment by rddunphy** [comment]
Is this project still maintained? useapassphrase.com is currently the second hit on Google for "passphrase generator", and the first hit (https://untroubled.org/pwgen/ppgen.cgi) is not nearly as user-friendly, so it would be good to know that issues like this are getting fixed!

**Comment by atoponce** [comment]
@rddunphy The last commit is 2015, unfortunately. Not to toot my own horn, but https://github.com/atoponce/webpassgen might be of interest?

**Comment by mike-hearn** [comment]
I haven't been maintaining it, but I'm hoping to find some spare time in the next few weeks to make updates, including updating the wordlist to use the EFF's [long word list](https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt) and fixing the algorithm's bias. Thanks to both of you for staying on top of this.

**Comment by mike-hearn** [comment]
This commit https://github.com/mike-hearn/useapassphrase/commit/0aa28d4f93c6e760abd4aad972c496bfbddc85c0 rewrites the way the site randomly chooses words; I believe this eliminates the bias, but let me know if you see any issues with it, and I'll re-open this ticket. Thanks again for flagging it.
